version: '3'

volumes:
  project:
    external: true
  appdynamics:
    external: true
  grafana_data:
    external: true

services:
  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #     - ../configs/grafana/dashboards:/var/lib/grafana/dashboards
  #     - ../configs/grafana/:/etc/grafana/
  #     - ../configs/grafana/provisioning:/etc/grafana/provisioning
  networkvizagent:
    # image: path/to/your/docker/image # docker registry image
    container_name: networkvizagent 
    network_mode: "host"
    build:
      context: ADCapital-NetworkAgent
      args:
       NETVIZ_ZIP_PKG: appd-netviz-x64-linux-21.3.0.2181.zip
    restart: unless-stopped 
    volumes:
      - project:/project
      - appdynamics:/appdynamics
    ports:
      - "3892:3892"
    env_file: ./docker-compose.env
    cap_add:
      - NET_ADMIN
      - NET_RAW
    extra_hosts:
      - "appdserver.demo.io:10.124.52.26"

  adcapitaldb:
    container_name: adcapitaldb
    hostname: adcapitaldb
    image: mysql:5.7
    logging:
      driver: "none"
    environment:
    - "MYSQL_ROOT_PASSWORD=welcome1"
    ports:
    - "3306:3306"
    extra_hosts:
      - "appdserver.demo.io:10.124.52.26"
    restart:
      always

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.5.4-management
    logging:
      driver: "none"
    environment:
    - "RABBITMQ_DEFAULT_USER=guest"
    - "RABBITMQ_DEFAULT_PASS=guest"
    ports:
    - "5672:5672"
    extra_hosts:
      - "appdserver.demo.io:10.124.52.26"
    restart:
      always