version: '3'

volumes:
  project:
    external: true
  appdynamics:
    external: true
  grafana_data:
    external: true

services:
  grafana:
    image: grafana/grafana:6.6.2
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ../configs/grafana/dashboards:/var/lib/grafana/dashboards
      - ../configs/grafana/:/etc/grafana/
      - ../configs/grafana/provisioning:/etc/grafana/provisioning
  project:
    container_name: project
    build:
      context: ADCapital-Project
    image: appdynamics/adcapital-project
    volumes:
    - project:/project
    extra_hosts:
      - "appdserver.demo.io:10.1.1.2"

  adcapitaldb:
    container_name: adcapitaldb
    hostname: adcapitaldb
    image: mysql:5.7
    logging:
      driver: "none"
    environment:
    - "MYSQL_ROOT_PASSWORD=welcome1"
    ports:
    - "3306:3306"
    extra_hosts:
      - "appdserver.demo.io:10.1.1.2"

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.5.4-management
    logging:
      driver: "none"
    environment:
    - "RABBITMQ_DEFAULT_USER=guest"
    - "RABBITMQ_DEFAULT_PASS=guest"
    ports:
    - "5672:5672"
    extra_hosts:
      - "appdserver.demo.io:10.1.1.2"

  rest:
    container_name: rest
    hostname: rest
    build:
      context: ./ADCapital-Tomcat
    image: appdynamics/adcapital-tomcat
    volumes:
    - project:/project
    - appdynamics:/appdynamics
    logging:
      driver: "none"
    env_file: ./docker-compose.env
    environment:
    - "ROLE=rest"
    - "APPDYNAMICS_AGENT_NODE_NAME=Rest"
    - "APPDYNAMICS_AGENT_TIER_NAME=Authentication-Service"
    depends_on:
    - "adcapitaldb"
    - "rabbitmq"
    ports:
    - "8081:8080"
    extra_hosts:
      - "appdserver.demo.io:10.1.1.2"

  portal:
    container_name: portal
    hostname: portal
    build:
      context: ./ADCapital-Tomcat
    image: appdynamics/adcapital-tomcat
    volumes:
    - project:/project
    - appdynamics:/appdynamics
    logging:
      driver: "none"
    env_file: ./docker-compose.env
    environment:
    - "ROLE=portal"
    - "APPDYNAMICS_AGENT_NODE_NAME=Portal"
    - "APPDYNAMICS_AGENT_TIER_NAME=Portal-Service"
    depends_on:
    - "adcapitaldb"
    - "rabbitmq"
    ports:
    - "8082:8080"
    extra_hosts:
      - "appdserver.demo.io:10.1.1.2"

  verification:
    container_name: verification
    hostname: verification
    build:
      context: ./ADCapital-Tomcat
    image: appdynamics/adcapital-tomcat
    volumes:
    - project:/project
    - appdynamics:/appdynamics
    logging:
      driver: "none"
    env_file: ./docker-compose.env
    environment:
    - "ROLE=verification"
    - "APPDYNAMICS_AGENT_NODE_NAME=Verification"
    - "APPDYNAMICS_AGENT_TIER_NAME=Verification-Service"
    depends_on:
    - "adcapitaldb"
    - "rabbitmq"
    ports:
    - "8083:8080"
    extra_hosts:
      - "appdserver.demo.io:10.1.1.2"

  processor:
    container_name: processor
    hostname: processor
    build:
      context: ./ADCapital-Tomcat
    image: appdynamics/adcapital-tomcat
    volumes:
    - project:/project
    - appdynamics:/appdynamics
    logging:
      driver: "none"
    env_file: ./docker-compose.env
    environment:
    - "ROLE=processor"
    - "APPDYNAMICS_AGENT_NODE_NAME=Processor"
    - "APPDYNAMICS_AGENT_TIER_NAME=LoanProcessor-Services"
    depends_on:
    - "adcapitaldb"
    - "rabbitmq"
    ports:
    - "8084:8080"
    extra_hosts:
      - "appdserver.demo.io:10.1.1.2"

  approval:
    container_name: approval
    hostname: approval
    build:
      context: ./ADCapital-Tomcat
    image: appdynamics/adcapital-tomcat
    volumes:
    - project:/project
    - appdynamics:/appdynamics
    logging:
      driver: "none"
    env_file: ./docker-compose.env
    environment:
    - "ROLE=approval"
    - "APPDYNAMICS_AGENT_NODE_NAME=Approval"
    - "APPDYNAMICS_AGENT_TIER_NAME=Approval-Services"
    depends_on:
    - "adcapitaldb"
    - "rabbitmq"
    ports:
    - "8085:8080"
    extra_hosts:
      - "appdserver.demo.io:10.1.1.2"

  load:
    container_name: adcapitalload
    hostname: adcapitalload
    build:
      context: ./ADCapital-Load
    image: appdynamics/adcapital-load
    env_file: ./docker-compose.env
    depends_on:
    - "portal"
    - "processor"
    extra_hosts:
      - "appdserver.demo.io:10.1.1.2"
    restart:
      always
