FROM appdynamics/adcapital-java:latest

ENV LOAD_GEN_HOME /AD-Capital-Load
RUN mkdir -p /AD-Capital-Load/build/distributions/
ADD /load-generator.zip /AD-Capital-Load/build/distributions/
RUN unzip AD-Capital-Load/build/distributions/load-generator.zip -d /
RUN chmod +x $LOAD_GEN_HOME/bin/*
ADD env.sh /
ADD startup.sh /
CMD ["/bin/bash","/startup.sh"]
